---
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    identityProviderURL: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_OJVQQhBQQ
    oAuthClientName: ${AUTH_CLIENT_NAME}
    oAuthSecret: ${AUTH_SECRET}
  server:
    cheServerIngress:
      annotations:
        cert-manager.io/cluster-issuer: che-certificate-issuer