---
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  networking:
    annotations:
      cert-manager.io/cluster-issuer: che-certificate-issuer
    auth:
      identityProviderURL: ${IDP_URL}
      oAuthClientName: ${AUTH_CLIENT_NAME}
      oAuthSecret: ${AUTH_SECRET}
  components:
    cheServer:
      debug: "true"
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: ${IDP_USER_CLAIM}
