---
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  networking:
    annotations:
      cert-manager.io/cluster-issuer: che-certificate-issuer
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    auth:
      identityProviderURL: ${IDP_URL}
      oAuthClientName: ${AUTH_CLIENT_NAME}
      oAuthSecret: ${AUTH_CLIENT_SECRET}
  components:
    cheServer:
      extraProperties:
        CHE_OIDC_USERNAME__CLAIM: ${IDP_USER_CLAIM}
    devfileRegistry:
      externalDevfileRegistries: [{ url: "https://veda-analytics-che-devfiles.s3.us-west-2.amazonaws.com/" } ]

