name: Staging Deploy

on:
  workflow_run:
    workflows: [Build Staging Docker Image]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      QUALIFIER: "staging"
      AUTH_CLIENT_NAME: ${{ secrets.AUTH_CLIENT_NAME_STAGING }}
      AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET_STAGING }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    container:
      image: 'ghcr.io/nasa-impact/veda-analytics-architecture:staging'
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Bootstrap account
        shell: bash
        run: |
          cd /opt
          make bootstrap
      - name: Install ctls
        shell: bash
        run: |
          cd /opt
          make install-dependencies
      - name: Deploy cloud infra
        shell: bash
        run: |
          cd /opt
          make deploy-cloud
      - name: Load K8s context
        run: |
          cd /opt
          make k8s
      - name: Test K8s cluster
        run: |
          kubectl get no
      - name: Deploy nginx ingresscontroller
        run: |
          cd /opt
          make deploy-nginx-ingresscontroller
      - name: Deploy cloud infra
        run: |
          cd /opt
          make deploy-che
